/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TransformOutput {
  code: string
  map?: string
}
export interface Caller {
  name?: string
  previousExport?: string
}
export interface State {
  filePath?: string
  componentName?: string
  caller?: Caller
}
export function transform(code: string, config: Buffer, state?: State | undefined | null): Promise<string>
