/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TransformOutput {
  code: string
  map?: string
}
export interface Config {
  icon?: boolean
}
export interface Caller {
  name?: string
  previousExport?: string
}
export interface Config {
  filePath?: string
  componentName?: string
  caller?: Caller
}
export function transform(code: string, config?: Config | undefined | null, state?: Config | undefined | null): Promise<string>
